config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  resources :listings, only: [:index, :new, :create] do
    resources :reviews, only: [:new, :create]
  end
  resources :bookings
  
  get '/bookings', to: 'bookings#index'

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  has_many :reviews, as: :reviewable
  belongs_to :user
  belongs_to :listing, foreign_key: :user_id, required: true

  before_validation :set_default_listing, on: :after_create

  after_create :calculate_duration_and_total_price

  private
  def set_default_listing
    self.listing ||= Listing.find_by(default: true)
  end

  def calculate_duration_and_total_price
    duration = (check_out.to_date - check_in.to_date).to_i
    total_price = duration * listing.price
    update(duration: duration, total_price: total_price)
  end
end

app/models/listing.rb
class Listing < ApplicationRecord
  belongs_to :user

  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }

  has_many :bookings, dependent: :destroy
  has_many :reviews, foreign_key: :user_id, as: :reviewable

  def average_raintg
    reviews.average(:rating).to_f
  end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :user
    belongs_to :listing, foreign_key: :user_id
    belongs_to :reviewable, polymorphic: true

    attribute :content, :string
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :listings
  has_many :bookings, foreign_key: :user_id, dependent: :destroy
  has_many :reviews, foreign_key: :user_id
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController

  def index
    @bookings = Booking.all
  end

  def new
    @listing = Listing.find_by(id: params[:listing_id])
    @booking = Booking.new
  end

  def create
    # binding.break
    @listing = Listing.find_by(id: params[:booking][:listing_id])
    puts "Listing ID: #{@listing&.id}"

    @booking = current_user.bookings.new(booking_params)
    puts "Booking Check-in: #{@booking&.check_in}"
    puts "Booking Check-out: #{@booking&.check_out}"
    
    @booking.listing_id = @listing.id

  #   if available_dates?(@booking.check_in, @booking.check_out, @listing)
  #     if @booking.save
  #       redirect_to booking_path(@booking), notice: "Booking created"
  #     else
  #       render :new
  #     end
  #   else
  #     redirect_to listings_path(@listing), notice: "Booking failed"
  #   end
  end

  private
    def booking_params
      params.require(:booking).permit(:listing_id, :check_in, :check_out)
    end

    # def available_dates?(ci_date, co_date, listing)
    #   if listing.present?
    #     overlap_bookings = listing.bookings.where(check_in: ci_date..co_date)
    #       .or(listing.bookings.where(check_out: ci_date..co_date))
    #     overlap_bookings.nil?
    #   else
    #     false
    #   end
    # end
    
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    def index
        @listings = Listing.all

        if params[:filter_by_location].present?
            @listings = @listings.where(location: params[:filter_by_location])
        end

        if params[:filter_by_check_in].present? && params[:filter_by_check_out].present?
            check_in_date = Date.parse(params[:filter_by_check_in])
            check_out_date = Date.parse(params[:filter_by_check_out])
            @listings = @listings.where("check_in_date <= ? AND check_out_date >= ?", check_in_date, check_out_date)
        end

        render :index
    end

end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @listings = Listing.all

    if params[:availability].present?
      @listings = @listings.where(availability: params[:availability])
    end

    if params[:location].present?
      @listings = @listings.where("location ILIKE ?", "%#{params[:location]}%")
    end

    if params[:check_in].present? && params[:check_out].present?
      check_in_date = Date.parse(params[:check_in])
      check_out_date = Date.parse(params[:check_out])
      @listings = @listings.joins(:bookings).where.not("bookings.check_out < ? OR bookings.check_in > ?", check_in_date, check_out_date)
    end
  end

  def show
    @listing = Listing.find(params[:id])
    @reviews = @listing.reviews
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_params)
    # binding.break
    if @listing.save
      redirect_to listings_path, notice: 'Listing was successfully created.'
    else
      render :new
    end
  end

  def edit
    @listing = Listing.find(params[:id])
  end

  def update
    @listing = Listing.find(params[:id])
    if @listing.update(listing_params)
      redirect_to @listing, notice: 'Listing was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    redirect_to listings_url, notice: 'Listing was successfully destroyed.'
  end

  private

  def listing_params
    params.require(:listing).permit(:title, :description, :price, :location)
  end
end

app/controllers/registration_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def create
      super do |resource|
        if resource.persisted?
          flash[:notice] = "Successfully signed up!"
        else
          flash[:alert] = "Registration failed. Please try again."
        end
      end
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
    def create
      super do |resource|
        if resource.persisted?
          flash[:notice] = "Successfully signed up!"
        else
          flash[:alert] = "Registration failed. Please try again."
        end
      end
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @listing = Listing.find(params[:listing_id])
    @review = Review.new
  end

  def create
    # binding.break
    @review = Review.new(review_params)
    @review.listing_id = params[:listing_id]
    @review.user = current_user
    if @review.save
      redirect_to @listing, notice: 'Review was successfully created.'
    else
      puts @review.errors.full_messages
      render :new
    end
  end

  def destroy
    @review = Review.find(params[:id])
    @listing = @review.listing
    @review.destroy
    redirect_to @listing, notice: 'Review was successfully destroyed.'
  end

  private

  def review_params
    params.require(:review).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/bookings/edit.html.erb
<h1>Edit Booking</h1>

<%= form_for @booking do |f| %>
  <div>
    <%= f.label :check_in %>
    <%= f.date_field :check_in %>
  </div>

  <div>
    <%= f.label :check_out %>
    <%= f.date_field :check_out %>
  </div>

  <div>
    <%= f.submit 'Update Booking' %>
  </div>
<% end %>

app/views/bookings/index.html.erb
<h1>All Bookings</h1>
<% @bookings.each do |booking| %>
  <h3>Booking Details</h3>
  <p>Check-in: <%= booking.check_in %></p>
  <p>Check-out: <%= booking.check_out %></p>
  <p>Duration: <%= booking.duration %> days</p>
  <p>Total Price: <%= booking.total_price %></p>
    <%= link_to t('bookings.leave_review'), new_listing_review_path(booking.listing_id, booking_id: booking.id) %>
<% end %>

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= form_for @booking do |f| %>
<%= f.hidden_field :listing_id, value: @listing.id %>
  <div>
    <%= f.label :check_in %>
    <%= f.date_field :check_in %>
  </div>

  <div>
    <%= f.label :check_out %>
    <%= f.date_field :check_out %>
  </div>

  <div>
    <%= f.submit 'Create Booking' %>
  </div>
<% end %>

app/views/bookings/show.html.erb
<h1>Booking Details</h1>

<p>Check-in: <%= @booking.check_in %></p>
<p>Check-out: <%= @booking.check_out %></p>
<p>Duration: <%= @booking.duration %> days</p>
<p>Total Price: <%= @booking.total_price %></p>

app/views/home/index.html.erb
<h1>this is home</h1>
<p>Thie is the home index for the fake airbnb</p>

<% if user_signed_in? %>
  <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
<% end %>
<hr>
<%= form_tag listings_path, method: :get do %>
  <div>
    <%= label_tag :availability, "Availability" %>
    <%= select_tag :availability, options_for_select([["All", ""], ["Available", "available"], ["Not Available", "not_available"]]) %>
  </div>
  <div>
    <%= label_tag :location, "Location" %>
    <%= text_field_tag :location %>
  </div>
  <div>
    <%= label_tag :check_in, "Check-in Date" %>
    <%= date_field_tag :check_in %>
  </div>
  <div>
    <%= label_tag :check_out, "Check-out Date" %>
    <%= date_field_tag :check_out %>
  </div>
  <div>
    <%= submit_tag "Filter Listings" %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Airbnbclone</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>

    <div class="container">
      <%= render 'shared/navbar' %>
        <p class="notice"><%= notice %></p>
        <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>
   
  </body>
</html>

app/views/listings/index.html.erb
<h1>All Listings</h1>

<% @listings.each do |listing| %>
  <h3><%= listing.title %></h3>
  <p><%= listing.description %></p>
  <p>Price: <%= listing.price %></p>
  <p>Location: <%= listing.location %></p>
<br>
  <% if current_user != listing.user %>
    <%= link_to "Book Now", new_booking_path(listing_id: listing.id), class: "btn btn-primary" %>
  <% end %>
  <br>
  <hr>
<% end %>
<%= link_to 'Add New Listing', new_listing_path %>
<br>
<%= link_to 'Go back to Home', root_path %>

app/views/listings/new.html.erb
<h1>Add New listing</h1>

<%= form_for @listing do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <br>
  <%= f.label :price %>
  <%= f.number_field :price %>
  <br>
  <%= f.label :location %>
  <%= f.text_field :location %>
  <br>
  <%= f.submit 'Create Listing' %>
<% end %>
<hr>
<%= link_to "View All Listings", listings_path %>
<br> 
<%= link_to 'Go back to Home', root_path %>

app/views/listings/show.html.erb
<h2>Reviews</h2>

    <% @reviews.each do |review| %>
       <h3>Rating: <%= review.rating %></h3>
       <p><%= review.comment %></p>
     <% end %>

     <h2>Average Rating: <%= @listing.average_rating %></h2>
     
     <h2>Add a Review</h2>
     <%= form_for [@listing, @listing.reviews.build] do |f| %>
       <div>
         <%= f.label :rating %>
         <%= f.number_field :rating, in: 1..5 %>
       </div>
       <div>
         <%= f.label :comment %>
         <%= f.text_area :comment %>
       </div>
       <div>
         <%= f.submit 'Create Review' %>
       </div>
     <% end %>

app/views/reviews/new.html.erb
<%= form_with(model: [@listing, @review], url: listing_reviews_path(@listing), method: :post) do |form| %>
  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <%= form.submit "Submit Review" %>
<% end %>

app/views/shared/_navbar.html.erb
    <nav class="navbar navbar-expand-lg navbar-light">
      <a class="navbar-brand" href="#">Airbnb</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">          
          <li class="nav-item">
            <a class="nav-link" href="/">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/bookings">My Booking</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="/listings">My Listing</a>
          </li>       
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li><a href="/users/sign_up">Sign Up</a></li>
            <li><a href="/users/sign_in">Login</a></li>
        </ul>      
      </div>
    </nav>